on:
  pull_request:
  push:
    branches:
      - master

name: Test and lint

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu, windows, macos]
    runs-on: ${{ matrix.os }}-latest
    name: "[${{ matrix.os }}] Test and lint"
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: 21
    - run: chmod +x gradlew
    - uses: gradle/actions/setup-gradle@v4
    - name: Run tests
      run: ./gradlew build check
