name: Publish snapshot

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: macos-latest
    name: "Publish snapshot to Central Portal"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - run: chmod +x gradlew
      - run: ./gradlew publishAggregationToCentralSnapshots --stacktrace
        env:
          PUBLISH_ALL_PLATFORMS: "true"
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_PRIVATE_KEY: ${{ secrets.SIGNING_PRIVATE_KEY }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
